import { XSSWhiteList } from '../types'

export const ALLOWED_ATTRIBUTES: XSSWhiteList = {
  'a': [
    'href',
    'target',
    'rel',
    'data-permlink',
    'data-tag',
    'data-author',
    'data-href',
    'data-community',
    'data-filter',
    'data-embed-src',
    'data-youtube',
    'data-start-time',
    'data-video-href',
    'data-proposal',
    'data-is-inline',
    'class',
    'title',
    'data-id',
    'id'
  ],
  'img': [
    'src',
    'alt',
    'class',
    'loading',
    'fetchpriority',
    'decoding',
    'itemprop'
  ],
  'span': ['class', 'id'],
  'iframe': ['src', 'class', 'frameborder', 'allowfullscreen', 'webkitallowfullscreen', 'mozallowfullscreen', 'sandbox'],
  'video': ['src', 'controls', 'poster'],
  'div': ['class', 'id'],
  'strong': [],
  'b': [],
  'i': [],
  'strike': [],
  'em': [],
  'code': [],
  'pre': [],
  'blockquote': ['class'],
  'sup': [],
  'sub': [],
  'h1': ['dir', 'id'],
  'h2': ['dir', 'id'],
  'h3': ['dir', 'id'],
  'h4': ['dir', 'id'],
  'h5': ['dir', 'id'],
  'h6': ['dir', 'id'],
  'p': ['dir', 'id'],
  'center': [],
  'ul': [],
  'ol': [],
  'li': [],
  'table': [],
  'thead': [],
  'tbody': [],
  'tr': [],
  'td': [],
  'th': [],
  'hr': [],
  'br': [],
  'del': [],
  'ins': []
}
