export const WHITE_LIST = [
  'ecency.com',
  'hive.blog',
  'peakd.com',
  'travelfeed.io',
  'dapplr.in',
  'leofinance.io',
  'inleo.io',
  'proofofbrain.io',
  'stemgeeks.net',
  'hiveblockexplorer.com',
  'proofofbrain.blog',
  'weedcash.network',
  'dapplr.in',
  'liketu.com',
  'bilpcoin.com',
  'inji.com'
]
export const OLD_LIST = [
  'busy.org',
  'steemit.com',
  'esteem.app',
  'steempeak.com',
  'partiko.app',
  'chainbb.com',
  'utopian.io',
  'steemkr.com',
  'strimi.pl',
  'steemhunt.com',
  'ulogs.org',
  'hede.io',
  'naturalmedicine.io'
]
